---
- name: Configure Nexus App Instance
  hosts: nexus-app
  gather_facts: false
  become: true

  pre_tasks:
    - name: Install python for Ansible to work
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  tasks:
    - name: Install Ruby
      apt:
        name: ruby-full
        state: present
        update_cache: yes

    - name: Install Bundler
      gem:
        name: bundler
        state: present
        user_install: no

    - name: Add APT key
      apt_key:
        url: https://pgp.mongodb.com/server-6.0.asc

    - name: Add MongoDB repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Start MongoDB
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Download Unit File for Nexus
      get_url:
        url: https://gist.githubusercontent.com/Artemmkin/ce82397cfc69d912df9cd648a8d69bec/raw/7193a36c9661c6b90e7e482d256865f085a853f2/nexus.service
        dest: /etc/systemd/system/nexus.service
